config/routes.rb
BusInf::Application.routes.draw do
  resources :reschedulings

  resources :messages

  resources :book_of_visits

  resources :book_of_classes

  resources :commentaries

  resources :comments

  get "sessions/new"

  get "users/new"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => "pages#contact"
  match '/faculty', :to => "pages#teacherpage"
  match '/messages', :to => "messages#index"

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :themes

  resources :module_of_disciplines

  resources :materials

  resources :interim_attestations

  resources :formation_of_competences

  resources :events

  resources :students

  resources :couples

  resources :disciplines

  resources :groups

  resources :specialities

  resources :competences

  resources :cell_skeds

  resources :advertisements

  resources :teachers

end

app/models/discipline.rb
# encoding: utf-8
class Discipline < ActiveRecord::Base
  has_many :formation_of_competences          , :dependent => :destroy
  has_many :interim_attestations           , :dependent => :destroy
  has_many :module_of_disciplines   , :dependent => :destroy
  has_many :themes
  #, :through => :module_of_disciplines
  has_many :couples
  belongs_to :speciality
  has_many :materials
  validates_presence_of :disc_name, :on => :create, :message => "Вписать название дисциплины"
  validates_presence_of :speciality_id, :on => :create, :message => "Выбрать специальность/направление подготовки"
  validates_presence_of :disc_semester, :on => :create, :message => "Вписать семестр преподавания"
  validates_presence_of :disc_course, :on => :create, :message => "Вписать курс преподавания"


  accepts_nested_attributes_for :module_of_disciplines, :allow_destroy => true

end

#accepts_nested_attributes_for :module_of_disciplines, :allow_destroy => true, :reject_if => lambda { |a| a[:content].blank? }


#has_attached_file :mfile

#public def publish_program(text)
#
#         m = File.new('app/assets/prog.html','a')
#         m.puts(text)
#
#         m.close
#
#
#       end

app/controllers/disciplines_controller.rb
# encoding: utf-8

class DisciplinesController < ApplicationController
  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disciplines }
    end
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discipline }
    end
  end

  # GET /disciplines/new
  # GET /disciplines/new.json
  def new
    @discipline = Discipline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @discipline }
    end
  end

  # GET /disciplines/1/edit

  def edit
    @discipline = Discipline.find(params[:id])
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(params[:discipline])

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to '/disciplines', notice: 'Дисциплина успешно добавлена' }
        format.json { render json: @discipline, status: :created, location: @discipline }
      else
        format.html { render action: "new" }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disciplines/1
  # PUT /disciplines/1.json
  def update
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      if @discipline.update_attributes(params[:discipline])
        format.html { redirect_to @discipline, notice: 'Дисциплина успешно обновлена' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy

    respond_to do |format|
      format.html { redirect_to disciplines_url }
      format.json { head :no_content }
    end
  end




end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<% @discipline.module_of_disciplines.build %>
<br />
<%= form_for(@discipline) do |f| %>
    <%= render 'shared/error_message', :target => @discipline %>



    <table width="80%">
      <tbody>
      <tr>
        <td align="right"><%= f.label "Название дисциплины" %></td>
        <td><%= f.text_field :disc_name, :class => "field" %></td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Выберите специальность" %></td>
        <td><%= f.select :speciality_id, Speciality.all.collect {|s| [s.spec_name, s.id]}, {:include_blank => 'Выберите специальность'}, {:class => "field"} %></td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Форма обучения:" %></td>
        <td><%= f.select :disc_cycle, %w[Очная  Заочная Вечерняя Очно-заочная], {:include_blank => 'Выберите форму обучения'}, {:class => "field"}  %></td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Курс преподавания" %></td>
        <td><%= f.text_field :disc_course, :class => "field" %>  </td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Семестр преподавания" %></td>
        <td><%= f.text_field :disc_semester, :class => "field" %>  </td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Цикл дисциплин преподавания" %></td>
        <td><%= f.select :disc_cycle, ['Гуманитарный, социальный и экономический цикл' , 'Математический и естественно-научный цикл','Профессиональный цикл','Физическая культура', 'Факультативы'], {:include_blank => 'Выберите цикл дисциплин'}, {:class => "field"} %> </td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Подцикл дисциплин преподавания" %></td>
        <td><%= f.select :disc_partofcycle, ['Базовая часть' , 'Вариативная часть'], {:include_blank => 'Выберите подцикл дисциплин'}, {:class => "field"} %> </td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Цели дисциплины" %></td>
        <td><%= f.text_area  :disc_objective, :class => "field" , :rows =>"5" , :cols =>"150"  %> </td>
      </tr>
      <tr>
        <td align="right"><%= f.label "Задачи дисциплины" %></td>
        <td><%= f.text_area  :disc_tasks, :class => "field" , :rows =>"5" , :cols =>"150"%> </td>
      </tr>
      </tbody>
    </table>

    <hr align="center"  noshade="true">

    <!--@mod=@discipline.module_of_disciplines.all()        -->
    <!--mod.each do |mod_form| -->



    <hr align="center"  noshade="true">




    <div class="actions">
      <%= f.submit "Сохранить"%>

    </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Редактирование рабочей программы дисциплины</h1>


<!--если надо, чтобы открывалась программа-->
<%= render 'form' %>

<!--если надо,чтобы открывалась обычная форма вместо program -->


<%= link_to 'Перейти к дисциплине', @discipline %> |
<%= link_to 'Назад', disciplines_path %>

app/views/disciplines/index.html.erb
<h1>Список преподаваемых дисциплин</h1>
<p id="notice"><%= notice %></p><br/>


<table>
  <tr>
    <th>Название</th>
    <th>Семестр</th>

  </tr>

  <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.disc_name %></td>
        <td align="center"><%= discipline.disc_semester %></td>
        <td><%= link_to 'Подробное описание', discipline %></td>
        <td><%= link_to 'Редактировать', edit_discipline_path(discipline) %></td>
        <td><%= link_to 'Удалить', discipline, confirm: 'Вы уверены?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Добавить дисциплину', new_discipline_path %>

app/views/disciplines/new.html.erb
<h1>Добавление рабочей программы дисциплины</h1>

<%= render 'form' %>

<%= link_to 'Назад', disciplines_path %>

app/views/disciplines/show.html.erb
<h1><%= @discipline.disc_name %></h1>
<p  id="notice"><%= notice %></p>



<h2 align="center"><i>Сведения о дисциплине:</i></h2>

<p>Специальность: <%= link_to @spec=Speciality.find(@discipline.speciality_id).spec_name, speciality_path(id=@discipline.speciality_id)  %>  </p><br/>


<p>Курс: <%= @discipline.disc_course %></p><br/>
<p>Семестр: <%= @discipline.disc_semester %></p><br/>

<% if @discipline.disc_cycle.nil? %>
<% else %>
    <p>Цикл дисциплин: <%= @discipline.disc_cycle %></p><br/>
<% end %>

<% if @discipline.disc_partofcycle.nil? %>
<% else %>
    <p>Подцикл дисциплин: <%= @discipline.disc_partofcycle %></p><br/>
<% end %>

<% if @discipline.disc_partofcycle.nil? %>
<% else %>
    <p>Цель курса: <%= @discipline.disc_objective %></p><br/>
<% end %>

<% if @discipline.disc_partofcycle.nil? %>
<% else %>
    <p>Задачи курса: <%= @discipline.disc_tasks %></p><br/>
<% end %>



<hr align="center"  noshade="true">

<div align="left" >
  <h2 align="center"><i>Формирование компетенций:       </i></h2>


  <strong><i>Компетенции, требуемые</i></strong> для освоения дисциплины:
  <br>
  <table >
    <tr>
      <th></th>
      <th>Содержание компетенции</th>
      <th>Знания</th>
      <th>Умения</th>
      <th>Навыки</th>
    </tr>
    <% foc=@discipline.formation_of_competences.all()

       foc.each do |formation_of_competence| %>
        <% if (formation_of_competence.foc_type?)%>
            <tr>
              <td width="6%" align="right"><%= link_to formation_of_competence.competence.comp_group,formation_of_competence %> :</td>
              <td width="43%"><%=formation_of_competence.competence.comp_name %></td>
              <td width="15%" align="left"><%= formation_of_competence.foc_knowledge %></td>
              <td width="15%" align="left"><%= formation_of_competence.foc_ability %></td>
              <td width="15%" align="left"><%= formation_of_competence.foc_skills %></td>
              <% if current_user.user_status == "teacher" %>
              <td width="6%" class="field" bgcolor="#f08080" align="center"><%= link_to '[X]', formation_of_competence, confirm: 'Удалить запись о формировании компетенции полностью?', method: :delete %></td>
              <%end %>
              </tr>
        <% end %>

    <%end %>
    <tr>
      <% if current_user.user_status == "teacher" %>
      <td bgcolor="#add8e6" class="field" align="center"><%= link_to '[+]', new_formation_of_competence_path  %></td>
      <%end %>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </table>
  <br/>
</div>


<div align="left">
  <strong><i>Компетенции, формируемые</i></strong> в процессе изучения дисциплины:
  <table>
    <tr>
      <th></th>
      <th>Содержание компетенции</th>
      <th>Знания</th>
      <th>Умения</th>
      <th>Навыки</th>
    </tr>
    <% foc=@discipline.formation_of_competences.all()
       foc.each do |formation_of_competence| %>
        <% if (formation_of_competence.foc_type?)%>
        <% else %>
            <tr>
              <td width="6%" align="right"><%= link_to formation_of_competence.competence.comp_group,formation_of_competence.competence %> :</td>
              <td width="43%"><%= formation_of_competence.competence.comp_name %></td>
              <td width="15%" align="left"><%= formation_of_competence.foc_knowledge %></td>
              <td width="15%" align="left"><%= formation_of_competence.foc_ability %></td>
              <td width="15%" align="left"><%= formation_of_competence.foc_skills %></td>
              <% if current_user.user_status == "teacher" %>
              <td width="6%" class="field" bgcolor="#f08080" align="center"><%= link_to '[X]', formation_of_competence, confirm: 'Удалить запись о формировании компетенции полностью?', method: :delete %></td>
              <% end %>
             </tr>
        <% end %>
    <%end %>
    <tr>
      <% if current_user.user_status == "teacher" %>
      <td bgcolor="#add8e6" class="field" align="center"><%= link_to '[+]', new_formation_of_competence_path  %></td>
      <%end %>
          <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </table>
  <br/>
</div>

<hr align="center"  noshade="true">




<h2 align="center"><i>Тематические модули дисциплины:</i></h2>
<table width="80%">
  <!--<tr>-->
  <!--<th></th>-->
  <!--<th>Модуль</th>-->
  <!--<th>Количество часов</th>-->
  <!--</tr>-->
  <%
     mod=@discipline.module_of_disciplines.all()
     mod.each do |module_of_discipline| %>
      <tr>
        <td width="6%" align="right"><%= module_of_discipline.mod_number %>) </td>
        <td width="70%"><%= link_to module_of_discipline.mod_name, module_of_discipline %></td>
        <td width="18%" align="center"><%= module_of_discipline.mod_numberofhours %> часов </td>
        <% if current_user.user_status == "teacher" %>
        <td width="6%" class="field" bgcolor="#f08080" align="center"><%= link_to '[X]', module_of_discipline, confirm: 'Удалить модуль полностью?', method: :delete %></td>
        <%end %>
        </tr>
  <%end %>
  <tr>
    <% if current_user.user_status == "teacher" %>
    <td bgcolor="#add8e6" class="field" width="5%" align="center"><%= link_to '[+]', new_module_of_discipline_path %></td>
    <%end %>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>
<br/>

<hr align="center"  noshade="true">
<h2 align="center"><i>Учебные и методические материалы:       </i></h2>
<ul>
  <li>Рабочая программа по дисциплине <%= link_to '(скачать)', materials_path %> </li>
  <li>Методические рекомендации к практическим занятиям <%= link_to '(скачать)', materials_path %> </li>


</ul>
<br />

<hr align="center"  noshade="true">
<%= link_to 'Бланк рабочей программы (в новом окне)', @discipline , {:target => "_blank"}%> |
<%= link_to 'Загрузить учебные и методические материалы', materials_path %> <br />

<%= link_to 'Редактировать сведения о дисциплине', edit_discipline_path(@discipline) %> |
<%= link_to 'Удалить дисциплину', @discipline, confirm: 'Вы уверены?', method: :delete %> <br />
<%= link_to 'К общему списку дисциплин', disciplines_path %>