config/routes.rb
BusInf::Application.routes.draw do
  resources :reschedulings

  resources :messages

  resources :book_of_visits

  resources :book_of_classes

  resources :commentaries

  resources :comments

  get "sessions/new"

  get "users/new"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => "pages#contact"
  match '/faculty', :to => "pages#teacherpage"
  match '/messages', :to => "messages#index"

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :themes

  resources :module_of_disciplines

  resources :materials

  resources :interim_attestations

  resources :formation_of_competences

  resources :events

  resources :students

  resources :couples

  resources :disciplines

  resources :groups

  resources :specialities

  resources :competences

  resources :cell_skeds

  resources :advertisements

  resources :teachers

end

app/models/theme.rb
# encoding: utf-8
class Theme < ActiveRecord::Base
  belongs_to :module_of_discipline
  belongs_to :discipline

  #validates_presence_of :theme_name, :on => :create, :message => "Вписать тему"
  #validates_presence_of :discipline_id, :on => :create, :message => "Выбрать дисциплину"
  #validates_presence_of :module_of_discipline_id, :on => :create, :message => "Выбрать модуль"

  #attr_accessible :theme_name, :theme_inmodule, :theme_indiscipline, :theme_numberofhour, :theme_technologytraining , :module_of_discipline_id, :discipline_id

  #accepts_nested_attributes_for :module_of_disciplines, :allow_destroy => true

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @themes }
    end
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
    @theme = Theme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theme }
    end
  end

  # GET /themes/new
  # GET /themes/new.json
  def new
    @theme = Theme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theme }
    end
  end

  # GET /themes/1/edit
  def edit
    @theme = Theme.find(params[:id])
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(params[:theme])

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render json: @theme, status: :created, location: @theme }
      else
        format.html { render action: "new" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /themes/1
  # PUT /themes/1.json
  def update
    @theme = Theme.find(params[:id])

    respond_to do |format|
      if @theme.update_attributes(params[:theme])
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme = Theme.find(params[:id])
    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_for(@theme) do |f| %>
    <% if @theme.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

          <ul>
            <% @theme.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label "Входит в дисциплину " %>
      <% def d_id  %>
      <% end %>
      <%
         #d_id=@theme.discipline.id
         f.select :discipline_id, Discipline.all.collect {|d| [d.disc_name, d.id]}, {:include_blank => 'Выберите дисциплину'}, {:class => "field"}
         #disc_id=Discipline.find(:discipline_id).module_of_discipline.id
         #@dis=@theme.discipline                убрала для скрина, ошибка
         #@theme.discipline_id=d_id

         #     убрала для скрина, ошибка f.select :module_of_discipline_id, ModuleOfDiscipline.find(discipline_id=@dis.id).collect  {|m| [m.mod_name, m.id]}, {:include_blank => 'Выберите модуль'}, {:class => "field"}

      %>

    </div>


    <div>
      <%= f.label "Входит в модуль " %>

      <%=  f.select :module_of_discipline_id, ModuleOfDiscipline.all().collect  {|m| [m.mod_name, m.id]}, {:include_blank => 'Выберите модуль'}, {:class => "field"}    %>
      <%= f.text_field :module_of_discipline_id%>
      <%= f.label "список модулей дисциплины: " %>
    </div>

    <!--здесь надо добавить модуль дисциплины-->


    <div>
      <%= f.label "Название темы" %>
      <%= f.text_area :theme_name, :rows=>3%>
    </div>
    <div>
      <%= f.label "Номер темы в плане модуля" %>
      <%= f.text_field :theme_inmodule %>
    </div>
    <div>
      <%= f.label "Номер темы в плане дисциплины" %>
      <%= f.text_field :theme_indiscipline %>
    </div>

    <div>
      <%= f.label "Количество часов на изучение:" %>
      <%= f.text_field :theme_numberofhour %>
    </div>
    <div>
      <%= f.label "Применяемые технологии преподавания:" %>
      <%= f.text_area :theme_technologytraining, :rows=>3 %>
    </div>



    <div class="actions">
      <%= f.submit "Сохранить" %>
    </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Редактирование темы</h1>

<%= render 'form' %>

<%= link_to 'Отменить', @theme %> |
<%= link_to 'К общему списку тем', themes_path %>

app/views/themes/index.html.erb
<h1>Общий список тем</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @themes.each do |theme| %>
      <tr>
        <td><%= link_to 'Показать', theme %></td>
        <td><%= link_to 'Редактировать', edit_theme_path(theme) %></td>
        <td><%= link_to 'Удалить', theme, confirm: 'Вы уверены?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Создать тему', new_theme_path %>

app/views/themes/new.html.erb
<p id="notice">
  <%= notice %>
  тема <strong>"<%= @theme.theme_name %>" </strong>
</p>
<br/>

<p>Входит в модуль <i> <%= link_to @theme.module_of_discipline.mod_name, module_of_discipline_path(@theme.module_of_discipline) %>    </i>
  дисциплины  <i><%= link_to @theme.discipline.disc_name, discipline_path(@theme.discipline) %></i></p>
<br/>



<%= link_to 'Редактировать', edit_theme_path(@theme) %> |
<%= link_to 'К общему списку тем', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>