config/routes.rb
BusInf::Application.routes.draw do
  resources :reschedulings

  resources :messages

  resources :book_of_visits

  resources :book_of_classes

  resources :commentaries

  resources :comments

  get "sessions/new"

  get "users/new"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => "pages#contact"
  match '/faculty', :to => "pages#teacherpage"
  match '/messages', :to => "messages#index"

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :themes

  resources :module_of_disciplines

  resources :materials

  resources :interim_attestations

  resources :formation_of_competences

  resources :events

  resources :students

  resources :couples

  resources :disciplines

  resources :groups

  resources :specialities

  resources :competences

  resources :cell_skeds

  resources :advertisements

  resources :teachers

end

app/models/teacher.rb
# encoding: utf-8
class Teacher < ActiveRecord::Base
  attr_accessible :teach_name, :teach_surname, :teach_secondname, :teach_rank, :teach_description, :teach_img
  has_attached_file :teach_img

  validates :teach_name, :presence => true, :length => {:maximum => 15}
  validates :teach_secondname, :presence => true, :length => {:maximum => 20}
  validates :teach_surname, :presence => true, :length => {:maximum => 30}
end

app/controllers/teachers_controller.rb
# encoding: utf-8
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to '/teachers', notice: 'Преподаватель успешно сохранен' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Данные о преподавателе успешно обновлены' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
    <%= render 'shared/error_message', :target => @teacher %>

    <div class="field">
      <%= f.label "Фамилия" %>
      <%= f.text_field :teach_surname %>
    </div>
    <div class="field">
      <%= f.label "Имя" %>
      <%= f.text_field :teach_name %>
    </div>
    <div class="field">
      <%= f.label "Отчество" %>
      <%= f.text_field :teach_secondname %>
    </div>
    <div class="field">
      <%= f.label "Звание" %>
      <%= f.text_area :teach_rank, :rows => 2 %>
    </div>
    <div class="field">
      <%= f.label "Описание" %>
      <%= f.text_area :teach_description, :rows => 6 %>
    </div>
    <div class="field">
      <%= f.label "Фото" %>
      <%= f.file_field :teach_img %>
    </div>


  <div class="actions">
    <%= f.submit :value => "Сохранить"%>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Список преподавателей</h1><br/>

<p id="notice"><%= notice %></p><br/>

<table>
  <tr>
    <th>Фамилия</th>
    <th>Имя</th>
    <th>Отчество</th>
    <th>Звание</th>
  </tr>

<% @teachers.each do |teacher| %>
  <tr>
    <td><%= teacher.teach_surname %></td>
    <td><%= teacher.teach_name %></td>
    <td><%= teacher.teach_secondname %></td>
    <td><%= teacher.teach_rank %></td>
    <td><%= link_to 'Посмотреть', teacher %></td>
    <td><%= link_to 'Редактировать', edit_teacher_path(teacher) %></td>
    <td><%= link_to 'Удалить', teacher, confirm: 'Действительно удалить?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить преподаватель', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>Данные о преподавателе</h1>

<%= render 'form' %>

<%= link_to 'Назад', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Редактировать', edit_teacher_path(@teacher) %> |
<%= link_to 'Назад', teachers_path %>