config/routes.rb
BusInf::Application.routes.draw do
  resources :reschedulings

  resources :messages

  resources :book_of_visits

  resources :book_of_classes

  resources :commentaries

  resources :comments

  get "sessions/new"

  get "users/new"

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => "pages#contact"
  match '/faculty', :to => "pages#teacherpage"
  match '/messages', :to => "messages#index"

  root :to => 'pages#home'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :themes

  resources :module_of_disciplines

  resources :materials

  resources :interim_attestations

  resources :formation_of_competences

  resources :events

  resources :students

  resources :couples

  resources :disciplines

  resources :groups

  resources :specialities

  resources :competences

  resources :cell_skeds

  resources :advertisements

  resources :teachers

end

app/models/module_of_discipline.rb
# encoding: utf-8
class ModuleOfDiscipline < ActiveRecord::Base
  belongs_to :discipline
  has_many :themes   , :dependent => :destroy

  #validates_presence_of :mod_name, :on => :create, :message => "Вписать название модуля"
  #validates_presence_of :discipline_id, :on => :create, :message => "Выбрать дисциплину"

  attr_accessible :mod_name, :mod_number, :mod_numberofhours, :discipline_id, :id



  #accepts_nested_attributes_for :discipline, :allow_destroy => true     ,    :reject_if => lambda { |a| a[:content].blank? }
  accepts_nested_attributes_for :themes, :allow_destroy => true,  :reject_if => lambda { |a| a[:content].blank? }


end

app/controllers/module_of_disciplines_controller.rb
class ModuleOfDisciplinesController < ApplicationController
  # GET /module_of_disciplines
  # GET /module_of_disciplines.json
  def index
    @module_of_disciplines = ModuleOfDiscipline.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @module_of_disciplines }
    end
  end

  # GET /module_of_disciplines/1
  # GET /module_of_disciplines/1.json
  def show
    @module_of_discipline = ModuleOfDiscipline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @module_of_discipline }
    end
  end

  # GET /module_of_disciplines/new
  # GET /module_of_disciplines/new.json
  def new
    @module_of_discipline = ModuleOfDiscipline.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @module_of_discipline }
    end
  end

  # GET /module_of_disciplines/1/edit
  def edit
    @module_of_discipline = ModuleOfDiscipline.find(params[:id])
  end

  # POST /module_of_disciplines
  # POST /module_of_disciplines.json
  def create
    @module_of_discipline = ModuleOfDiscipline.new(params[:module_of_discipline])

    respond_to do |format|
      if @module_of_discipline.save
        format.html { redirect_to @module_of_discipline, notice: 'Module of discipline was successfully created.' }
        format.json { render json: @module_of_discipline, status: :created, location: @module_of_discipline }
      else
        format.html { render action: "new" }
        format.json { render json: @module_of_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /module_of_disciplines/1
  # PUT /module_of_disciplines/1.json
  def update
    @module_of_discipline = ModuleOfDiscipline.find(params[:id])

    respond_to do |format|
      if @module_of_discipline.update_attributes(params[:module_of_discipline])
        format.html { redirect_to @module_of_discipline, notice: 'Module of discipline was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @module_of_discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /module_of_disciplines/1
  # DELETE /module_of_disciplines/1.json
  def destroy
    @module_of_discipline = ModuleOfDiscipline.find(params[:id])
    @module_of_discipline.destroy

    respond_to do |format|
      format.html { redirect_to module_of_disciplines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/module_of_disciplines_helper.rb
module ModuleOfDisciplinesHelper
end

app/views/module_of_disciplines/_form.html.erb
<br />
<%= form_for(@module_of_discipline) do |f| %>
    <% if @module_of_discipline.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@module_of_discipline.errors.count, "error") %> prohibited this module_of_discipline from being saved:</h2>

          <ul>
            <% @module_of_discipline.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label "Номер модуля в дисциплине" %>
      <%= f.text_field :mod_number%>
    </div>

    <br/>

    <div>
      <%= f.label "Дисциплина" %>
      <%= f.select :discipline_id, Discipline.all.collect {|d| [d.disc_name, d.id]}, {:include_blank => 'Выберите дисциплину'}, {:class => "field"}
      %>
    </div>

    <br/>

    <div>
      <%= f.label "Название модуля" %>

      <%= f.text_field :mod_name%>
    </div>
    <br/>




    <div>
      <%= f.label "Количество часов на освоение модуля" %>
      <%= f.text_field :mod_numberofhours%>
    </div>

    <br/>



    <div class="actions">
      <%= f.submit "Сохранить модуль" %>
    </div>
<% end %>

app/views/module_of_disciplines/edit.html.erb
<h1>Редактирование модуля дисциплины</h1>

<%= render 'form' %>

<%= link_to 'Показать', @module_of_discipline %> |
<%= link_to 'Назад', module_of_disciplines_path %>

app/views/module_of_disciplines/index.html.erb
<h1>Список модулей по всем дисциплинам</h1>

<table>
  <tr>
    <th>Дисциплина</th>
    <th width="7%">Номер модуля в дисциплине</th>
    <th>Название модуля</th>
    <th width="7%">Количество часов</th>
  </tr>

  <% @module_of_disciplines.each do |module_of_discipline| %>
      <tr>
        <td><%= link_to module_of_discipline.discipline.disc_name, module_of_discipline.discipline %></td>
        <td align="center"><%= module_of_discipline.mod_number %></td>
        <td><%= module_of_discipline.mod_name %> </td>
        <td align="center"><%= module_of_discipline.mod_numberofhours %></td>
        <td><%= link_to 'Показать', module_of_discipline %></td>
        <td><%= link_to 'Редактировать', edit_module_of_discipline_path(module_of_discipline) %></td>
        <td><%= link_to 'Удалить', module_of_discipline, confirm: 'Вы уверены?', method: :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Добавить модуль дисциплины', new_module_of_discipline_path %>

app/views/module_of_disciplines/new.html.erb
<h1>Добавление модуля в дисциплину</h1>

<%= render 'form' %>

<%= link_to 'Назад', module_of_disciplines_path %>

app/views/module_of_disciplines/show.html.erb
<p id="notice">
  <%= notice %>
  модуль <strong>"<%= @module_of_discipline.mod_name %>" </strong>
</p>





<p>включен в дисциплину <i> <%= link_to @module_of_discipline.discipline.disc_name, discipline_path(@module_of_discipline.discipline) %></i></p>

<br/>
<p>Номер в дисциплине: <%= @module_of_discipline.mod_number %></p>
<br/>
<p>Количество часов на освоение: <%= @module_of_discipline.mod_numberofhours %></p><br/>
<br/>

<hr align="center"  noshade="true">
<p>Темы, составляющие модуль:</p>
<table>
  <tr>
    <th></th>
    <th>Тема</th>
    <th>Количество часов</th>
  </tr>
  <%
     them=@module_of_discipline.themes.all()
     them.each do |theme| %>
      <tr>
        <td width="3%"><%= theme.theme_inmodule %>) </td>
        <td width="71%"><%= link_to theme.theme_name, theme %></td>
        <td  align="center" width="23%"><%= theme.theme_numberofhour %> </td>
        <td width="3%" class="field" bgcolor="#f08080"><%= link_to '|X|', theme, confirm: 'Удалить тему полностью?', method: :delete %></td>

      </tr>
  <%end %>

  <tr>
    <td bgcolor="#add8e6" class="field"><%= link_to '|+|', new_theme_path  %></td>
    <td></td>
    <td></td>
  </tr>
</table>
<br/>

<hr align="center"  noshade="true">

<%= link_to 'Редактировать', edit_module_of_discipline_path(@module_of_discipline) %> |
<%= link_to 'К общему списку модулей', module_of_disciplines_path %>